spring.application.name = Antares
spring.datasource.username = antares_user
spring.datasource.password = antares
spring.datasource.url = jdbc:postgresql://localhost:5432/db_antares?serverTimezone=America/Sao_Paulo
spring.jpa.properties.hibernate.jdbc.time_zone = America/Sao_Paulo
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show_sql = false